Code-Poets/sheetstorm

users/templates/base.html
users/templates/users_list.html

Resolves https://github.com/Code-Poets/sheetstorm/issues/67
Some of the strings doesn't exist anymore in master branch.

Change names in UI

---

utils/base_tests.py

Fix timezone related bug in automated datetime field test

---

managers/templates/managers/project_detail.html
managers/templates/managers/projects_list.html
managers/tests/test_unit_managers_apiview.py
managers/urls.py
managers/views.py

Feature project detail view

---

employees/models.py
employees/templates/employees/report_list.html
requirements.lock
requirements.txt
sheetstorm/settings/base.py

Resolves https://github.com/Code-Poets/sheetstorm/issues/36
Related #106

Feature support markdown in report description

---

managers/models.py
managers/tests/test_unit_project_signals.py
users/models.py
users/static/users/scripts/update_account_popup.js
users/templates/users_detail.html
users/templates/users_list.html
users/tests/test_unit_customuser_signals.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/65

Bug automatic user type

---

.gitignore

Add `.idea/` dir to .gitignore

---

find-files-to-refactor.sh
full-check.sh
lint.sh
pylintrc
requirements.lock
requirements.txt
style.sh

There is no issue for that. I have added few improvements to our programming tools. They should make our job easier :)

Chore improve projects programming tools

---

employees/common/strings.py
employees/common/validators.py
employees/forms.py
employees/models.py
employees/serializers.py
employees/tests/test_unit_report_model.py
employees/tests/test_unit_report_serializer.py
employees/tests/test_unit_report_viewset.py
employees/views.py
managers/models.py
managers/tests/test_api.py
managers/tests/test_unit_model.py
managers/views.py
mypy.ini
users/common/exceptions.py
users/common/model_helpers.py
users/common/utils.py
users/models.py
users/permissions.py
users/serializers.py
users/templatetags/user_type_tags.py
users/tests/test_unit_customuser_model.py
users/tests/test_unit_customuser_serializer.py
users/tests/test_unit_users_permissions.py
users/tests/test_user_login.py
users/tests/test_utils_functions.py
users/views.py
utils/base_tests.py
utils/decorators.py
utils/sample_data_generators.py

Resolves https://github.com/Code-Poets/sheetstorm/issues/35

Bugfix pylint flake8 and mypy warnings

---

employees/models.py
employees/templates/employees/report_list.html
requirements.lock
requirements.txt
sheetstorm/settings/base.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/109
Now I think that markdown works better, especially text display looks much better. I've changed framework which is used and I added extensions which allow to use checkboxes, tables and few more options.

Bug fix markdown problems

---

employees/tests/test_unit_report_viewset.py
employees/views.py

Current date is now being filled in report creation form in reports' list view.

Feature default date input

---

.gitignore

Small PR to prevent showing generated static files in git-cola.

Add SheetStorm static files to gitignore

---

employees/templates/employees/author_report_list.html
employees/templates/employees/report_detail.html
employees/templates/employees/report_list.html
managers/templates/managers/project_detail.html
managers/templates/managers/projects_list.html
users/templates/signup.html
users/templates/user_create.html
users/templates/user_update.html
users/templates/users_detail.html
users/templates/users_list.html

**Done**
- Fixes issues with malfunctioning .js and .css files by moving them to appropriate blocks in affected templates.
- Remaining templates are edited for consistency.

Bugfix refactor templates for proper javascript usage

---

managers/models.py

No issue for this.
I made this `PR` because I note that sometimes our handlers doesn't work good. If in our pk_set first of users was manager this method make return and didn't make changes to other users which was employee.

Bugfix small changes in manager handlers.

---

users/templates/users_detail.html

Resolves: https://github.com/Code-Poets/sheetstorm/issues/171

Bugfix changed sended pk while editing user in admin update template

---

users/common/utils.py
users/models.py
users/permissions.py
users/serializers.py
users/views.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/148
**After review I will change branch name because I thought that this is feature.**

Chore add logs to user app

---

users/urls.py
users/views.py

Resolves https://github.com/Code-Poets/sheetstorm/issues/94

Remove `api_root` view and related code

---

managers/forms.py
managers/tests/test_views.py
managers/views.py

Resolves https://github.com/Code-Poets/sheetstorm/issues/28

Fix for access to editing managers list and update tests

---

employees/static/employees/style.css
employees/templates/employees/author_report_list.html
employees/templates/employees/project_report_list.html
employees/templates/employees/report_list.html
users/templates/base.html

Adds appropriate parameters to template elements to only show desired elements on print (report lists).
Related #135 
**Do not delete this branch until #137 is merged**

Feature adjust templates for printing

---

users/templates/home.html
users/views.py

resolves: https://github.com/Code-Poets/sheetstorm/issues/186

Remove visit counter from user's home view

---

users/templates/users_list.html
users/tests/test_unit_users_apiview.py
users/tests/test_views.py
users/views.py
utils/decorators.py

I have change view to django generic view, but I have one business question: Only Admin should be able get employees list? @Karrp

Change UserList view from Rest APIView to Django DetailView

---

full-check.sh

Fix `full-check.sh` - add shebang line

---

employees/forms.py

resolves: https://github.com/Code-Poets/sheetstorm/issues/192

Disable possibility to change report's author by Admin user

---

full-check.sh

Add errexit flag to full-check script

---

employees/templatetags/data_display_filters.py
managers/views.py
users/views.py
utils/decorators.py

Fix mypy warnings

---

employees/tests/test_unit_report_viewset.py
employees/views.py

Resolves #222 
All serializer creation is now done via _create_serializer method. Now each time serializer is instantiated, all required filtrations on it's fields' querysets are performed.
Done:
- All instances of serializer creation have been moved to the `_create_serializer` method

Bugfix wrong projects displayed after report creation fail

---

lint.sh

Resolves: https://github.com/Code-Poets/sheetstorm/issues/226
**Should be done**
- add to ignore `W503` error

Bugfix-flake8-error

---

managers/models.py
managers/views.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/154
I have add few methods, because I couldn't add any logs when something would happen

Chore add logs to manager app

---

users/models.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/211

Bugfix change type annotations for get_reports_created

---

users/common/exceptions.py
users/common/strings.py
users/common/utils.py
users/forms.py
users/models.py
users/serializers.py
users/static/users/scripts/redirect_to_home_page.js
users/templates/accounts/success-registration.html
users/templates/partials/errors_in_field.html
users/templates/signup.html
users/tests/test_unit_customuser_model.py
users/tests/test_unit_users_apiview.py
users/tests/test_utils_functions.py
users/tests/test_views.py
users/urls.py
users/views.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/144
Template doesn't look good but I just created it to test, I have already done in PR my singup interface, after review I just need to add few things in new interface.

Chore refactor singup view

---

employees/common/strings.py
employees/models.py
employees/templates/employees/author_report_list.html
employees/templates/employees/project_report_list.html
employees/templates/employees/report_list.html
employees/tests/test_unit_report_model.py
employees/views.py

Introduces total hours per month counter for all report list views.
Related #138

Feature hours per month counter

---

employees/tests/test_unit_report_viewset.py
employees/views.py

resolves: https://github.com/Code-Poets/sheetstorm/issues/223

Fix creating report in `ReportList` view and adapt test

---

users/templates/user_create.html
users/tests/test_unit_users_apiview.py
users/tests/test_views.py
users/views.py

resolves: https://github.com/Code-Poets/sheetstorm/issues/246

Change `UserCreate` from `APIView` to Django `CreateView` 

---

requirements.lock

Fix psycopg requirements

---

common/convert.py
employees/templates/employees/author_report_list.html
employees/templates/employees/report_list.html

No issue for that. Problem was with converting timedelta value if this value was bigger than 24 hours.

Fix converting timedelta to string

---

sheetstorm/fixtures/site.yaml
sheetstorm/settings/production.py

Bug occurred during data migrations. Everything should be added as fixture.

Bugfix add site id fixture

---

RELEASE-NOTES.md

Update release notes for v0.4.0 release

---

employees/common/strings.py
employees/forms.py
employees/templates/employees/report_detail.html
employees/tests/test_unit_report_viewset.py
employees/tests/test_views.py
employees/urls.py
employees/views.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/245
**Done**
- update should work
- template should display and allow to send post only for users belonging to given projects
- django view

Chore refactor report detail view

---

common/convert.py
employees/common/strings.py
employees/forms.py
employees/serializers.py

Idea on this task created by users which wanted to add work_hours time as only hours. 
Done:
- changed way how work_hours converter works
- move function to convert to common dir

Chore Add posibility to add as work hours only hours

---

employees/templates/employees/admin_report_detail.html

Resolves: https://github.com/Code-Poets/sheetstorm/issues/242

Bugfix - Add discard button to admin report detail

---

users/templates/users_detail.html
users/tests/test_unit_users_apiview.py
users/tests/test_views.py
users/views.py

resolves: https://github.com/Code-Poets/sheetstorm/issues/248

Change `UserUpdateByAdmin` to be Django class based view 

---

employees/static/employees/scripts/basic_popup_window.js
employees/templates/employees/report_detail.html

Resolves: https://github.com/Code-Poets/sheetstorm/issues/278
I am not sure if I did it in proper way. I saw some examples with AJAX but it doesn't work in my implementation so I decided to make it like that way.

Bugfix delete button to send it as a post method

---

employees/templates/employees/project_report_list.html

Resolves: https://github.com/Code-Poets/sheetstorm/issues/243

Bugfix add return button in project report list

---

employees/common/exports.py
employees/templates/employees/author_report_list.html
employees/templates/employees/project_report_list.html
employees/templatetags/data_display_filters.py
employees/tests/test_unit_export_data.py
employees/tests/test_unit_templatetags.py
employees/urls.py
employees/views.py
utils/tests/test_access_permissions.py

There was a bug with generating xlsx reports.

Bugfix generating xlsx for one month

---

RELEASE-NOTES.md

Chore update release notes for version v0.5.0

---

users/templates/base.html
users/templates/users_list.html
users/tests/test_views.py

resolves: https://github.com/Code-Poets/sheetstorm/issues/100

Change dipslay of `user_type` to be human readable

---

RELEASE-NOTES.md
employees/tests/test_views.py
requirements.lock
requirements.txt

resolves: https://github.com/Code-Poets/sheetstorm/issues/298

Update `Django` to `2.2.2` and adapt test

---

employees/templates/employees/author_report_list.html

Done:
- markdown_description property has been passed to template
Resolves #304

Pass markdown_description property to template

---

employees/forms.py
employees/templates/employees/report_list.html
employees/tests/test_views.py
employees/urls.py
employees/views.py

resolves: https://github.com/Code-Poets/sheetstorm/issues/244

Change `ReportList` to `ReportListCreateProjectJoinView` (DCBV)

---

employees/tests/test_views.py
employees/views.py

resolves: https://github.com/Code-Poets/sheetstorm/issues/321
should be merged **after**: https://github.com/Code-Poets/sheetstorm/pull/296

Bugfix navigation bar

---

requirements.lock
requirements.txt
sheetstorm/settings/base.py
sheetstorm/settings/development.py
users/forms.py
users/static/users/scripts/captcha-refresh.js
users/templates/signup.html
users/tests/test_views.py
users/urls.py

No issue for that. It is security feature for registration.

Add captcha to registration view

---

managers/templates/managers/project_detail.html

Resolves https://github.com/Code-Poets/sheetstorm/issues/143

Fix for incorrect html tag

---

employees/common/constants.py
employees/common/exports.py
employees/factories.py
employees/tests/test_unit_export_data.py

resolves: https://github.com/Code-Poets/sheetstorm/issues/310

Feature better export of reports

---

employees/templates/employees/report_list.html
employees/templatetags/data_display_filters.py
employees/tests/test_unit_templatetags.py
employees/views.py
utils/tests/test_access_permissions.py

The idea of this feature came after way of delivering monthly reports has been changed. Every user should have possibility to export his own reports.

Add possibility to export monthly reports for every user

---

employees/static/employees/style.css
employees/templates/employees/report_list.html

Resolves: https://github.com/Code-Poets/sheetstorm/issues/306

Bugfix make hyperlink highlighted

---

users/static/users/center_style.css

Resolves: https://github.com/Code-Poets/sheetstorm/issues/301

Bugfix hide toggle button

---

users/common/constants.py
users/forms.py
users/static/users/center_style.css
users/templates/signup.html
users/urls.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/282

Feature rebuild register interface

---

employees/templatetags/data_display_filters.py
employees/tests/test_unit_templatetags.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/295

Chore change `extract_year_and_month_from_url`

---

sheetstorm-deployment/consts.yml
sheetstorm-deployment/roles/postgres_backup/tasks/main.yml
sheetstorm-deployment/roles/postgres_backup/templates/pg_backup.sh.j2

Please consulting with me before merged.

Feature add encryption to postgres backups

---

employees/tests/test_unit_export_data.py
employees/views.py

Resolves https://github.com/Code-Poets/sheetstorm/issues/336

Add security for exporting own reports

---

employees/common/strings.py
employees/templates/employees/author_report_list.html
employees/templates/employees/partial/projects_work_percentage.html
employees/templates/employees/report_list.html
employees/tests/test_unit_report_model.py
employees/views.py
users/models.py
utils/mixins.py
utils/tests/test_mixins.py

Resolves https://github.com/Code-Poets/sheetstorm/issues/147

Feature percentage time of worker for each project

---

employees/common/exports.py
employees/tests/test_unit_export_data.py
pytest.ini

Number of warnings which we got when we run `full-check` script was crazy and made me nervous :P So I decided to do cleaning :)

Chore get rid of pytest warnings

---

employees/forms.py
employees/tests/test_views.py

Resolves: #203 
should be merged after #327

Feature default task activity for new report

---

employees/static/employees/style.css
employees/templates/employees/author_report_list.html
employees/templates/employees/report_list.html

Resolves https://github.com/Code-Poets/sheetstorm/issues/190

Feature add day name to reports

---

employees/tests/test_views.py
employees/views.py

Resolves https://github.com/Code-Poets/sheetstorm/issues/350 https://github.com/Code-Poets/sheetstorm/issues/351

Bugfix when admin edit someone report become owner of this report

---

employees/templates/employees/report_list.html

Bugfix calendar widget display in `report-list`

---

users/templates/registration/login.html

Resolves: https://github.com/Code-Poets/sheetstorm/issues/251
All other form are displayed by crispy filter so we have to remember about it during frontend refactor

Chore unify display errors in form

---

employees/forms.py
employees/tests/test_views.py

Resolves https://github.com/Code-Poets/sheetstorm/issues/376

Fix for on report editing, the task activity is set to default

---

employees/common/constants.py
employees/common/strings.py
employees/forms.py
employees/models.py
employees/tests/test_unit_report_model.py
mypy.ini

Resolves https://github.com/Code-Poets/sheetstorm/issues/367

Bugfix add more restrict setting work_hours value

---

employees/common/exports.py
mypy.ini

Chore add type annotations in exports.py file

---

employees/common/constants.py
employees/forms.py
employees/views.py
managers/commons/constants.py
managers/models.py
managers/tests/test_unit_model.py
users/common/constants.py
users/forms.py
users/models.py
users/tests/test_unit_customuser_model.py
users/tests/test_views.py
users/urls.py

Chore change classes to enums in constants

---

employees/forms.py

Bugfix missing work hours during updating reports

---

employees/templates/employees/author_report_list.html
managers/templates/managers/projects_list.html
users/templates/base.html

Bugfix change names in UI

---

employees/common/exports.py
employees/models.py

Chore change type annotation from Decimal to timedelta

---

notifications/apps.py
notifications/urls.py
sheetstorm/settings/base.py
sheetstorm/urls.py

Feature Add NotificationsApp

---

employees/templates/employees/author_report_list.html
employees/templates/employees/project_report_list.html
employees/templates/employees/report_list.html
employees/templatetags/data_display_filters.py
employees/tests/test_unit_custom_mixins.py
employees/tests/test_unit_templatetags.py
employees/tests/test_views.py
employees/urls.py
employees/views.py
managers/templates/managers/project_detail.html
users/templates/base.html

Resolves: https://github.com/Code-Poets/sheetstorm/issues/309
**Should be done**
- Add view for author reports project with filtered reports
- Add export view to dowload only reports from current project
- Add permissions for Admin and manager of project
- Create base view and add inheritance from `AuthorReportProjectView` and `AuthorReportView`
- Make boxes clickable
Thanks in advanced for your feedback :)

Feature add clickablex boxes to members project

---

employees/templates/employees/project_report_detail.html
employees/templates/employees/report_detail.html
employees/templates/employees/report_list.html
users/templates/base.html

No issue for that - quick fix for problem found by @Karrp  (hours mask was not applied in all views)

Bugfix work hours display in report update

---

employees/common/constants.py
employees/common/exports.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/370
There is PR which is related to this one.
Related: https://github.com/Code-Poets/sheetstorm/pull/426

Bugfix OpenOffice does not display full description

---

employees/tests/test_views.py
employees/views.py

Bugfix weekends should be skipped in reports date suggestion

---

employees/common/strings.py

Change "Recent month" to "Current month" in month navigation bar

---

sheetstorm/settings/base.py
sheetstorm/tests/test_views.py
sheetstorm/urls.py
sheetstorm/views.py
users/urls.py
users/views.py
utils/tests/test_access_permissions.py

Bugfix login and home urls

---

employees/models.py
employees/templates/employees/author_report_list.html
employees/templates/employees/project_report_list.html
employees/templates/employees/report_list.html
employees/tests/test_unit_export_data.py
employees/urls.py
employees/views.py
managers/models.py
users/models.py
utils/tests/test_access_permissions.py

No issue for this.
I have to create export view for authors in project.
It was due to this issue: https://github.com/Code-Poets/sheetstorm/issues/309
I also fixed naming of files: because It always took current date. I think when I would like to export reports from June I would like to have it named as `06_2019` not `07_2019`

Feature add export to project author report project view

---

employees/common/constants.py
employees/common/exports.py

Resolves:https://github.com/Code-Poets/sheetstorm/issues/435
I also change horizontal alignment in hours field because it wasn't look good in printing mode.

Feature add lines separators in columns

---

common/constants.py
sheetstorm/apps.py
sheetstorm/settings/base.py
sheetstorm/system_check.py
utils/tests/test_system_check.py

Resolves: https://github.com/Code-Poets/sheetstorm/issues/358
In issue I describe what to do.

Chore add system checks

---

users/templates/base.html

Resolve: https://github.com/Code-Poets/sheetstorm/issues/444

Bugfix set active actual url

---

users/templates/base.html

Resolves #452 
Done:
------------
-  `My Reports` -> `Reports`

Change name from 'My Reports' to 'Reports'

---

check-environment-packages.sh
full-check.sh

Small improvement for testing purposes :)

Chore add virtual environments packages checks

---

sheetstorm-deployment/roles/configure_sheetstorm_environment/tasks/update-sheetstorm-application.yml
sheetstorm-deployment/roles/install_dependencies_and_basic_configuration/tasks/main.yml
sheetstorm-deployment/versions.yml

Chore install python packages by using pipenv instead of pip

---

check-environment-packages.sh

Small improvement but still improvement. Now script reminds to activate shell if it's not activated already.

Chore Improvement to check-environment-packages script

---

employees/tests/test_unit_custom_mixins.py
employees/views.py
utils/mixins.py
utils/tests/test_mixins.py

No issue for that, fixes bug from sentry: http://35.242.195.123/sentry/sheetstorm/issues/5127/

Bugfix month navigation

---

employees/tests/test_views.py
sheetstorm/settings/base.py

Bugfix failing  tests in master

---

users/templates/registration/login.html
users/templates/signup.html

resolves: https://github.com/Code-Poets/sheetstorm/issues/454

Bugfix modify template to preserve user's email in case of errors

---

users/templates/registration/login.html
users/templates/signup.html

Bugfix none displayed in login form

---

sheetstorm-deployment/configure-sheetstorm-server.yml
sheetstorm-deployment/create-compute-instance-for-sheetstorm.yml
sheetstorm-deployment/templates/upload-postgresql-backup-to-gcloud-bucket.sh.j2

Feature add script and cron job that automatically upload postgresql backup to the google cloud storage

---

employees/tests/test_unit_custom_mixins.py
employees/views.py

no issue for that: resolves sentry issues: http://35.242.195.123/sentry/sheetstorm/issues/5129/?query=is%3Aunresolved and http://35.242.195.123/sentry/sheetstorm/issues/5128/?query=is%3Aunresolved

Fix navigation form (in case of malformed date)

---

employees/common/constants.py
employees/common/exports.py
employees/tests/test_unit_export_data.py

Resolve: https://github.com/Code-Poets/sheetstorm/issues/372
Related: https://github.com/Code-Poets/sheetstorm/pull/481

Chore remove daily hours from export

---

employees/common/exports.py

Resolve: https://github.com/Code-Poets/sheetstorm/issues/477

Add top border to separate days in excel reports

---

employees/common/constants.py
employees/common/exports.py
employees/tests/test_unit_export_data.py
employees/views.py

Resolve: https://github.com/Code-Poets/sheetstorm/issues/433

Feature export csv for project as one file

---

employees/static/employees/style.css
employees/templates/employees/author_report_list.html
employees/templates/employees/report_list.html

Resolves: https://github.com/Code-Poets/sheetstorm/issues/482

Bugfix incorrect display of reports

---

sheetstorm-deployment/roles/configure_nginx/templates/maintenance-remote.j2
sheetstorm-deployment/roles/configure_nginx/templates/modsecurity_configs/main.conf.j2
sheetstorm-deployment/roles/configure_nginx/templates/sheetstorm-remote.j2

Chore improve nginx security

---

sheetstorm-deployment/consts.yml
sheetstorm-deployment/roles/configure_nginx/templates/maintenance-remote.j2
sheetstorm-deployment/roles/configure_nginx/templates/sheetstorm-remote.j2

Chore add headers that improve security in nginx

---

employees/forms.py
employees/templates/employees/project_report_detail.html
employees/templates/employees/report_detail.html
employees/tests/test_views.py
employees/views.py
managers/models.py
managers/tests/test_unit_model.py
managers/tests/test_unit_project_signals.py

Resolve: https://github.com/Code-Poets/sheetstorm/issues/519

Bugfix completed and suspended projects

---

managers/templates/managers/projects_list.html

No issue for this
This button should be displayed only for admin.

Bugfix hide create project for managers

---

employees/templates/employees/partial/display_reports/reports_in_date_for_author.html

Add linebreaks filter to reports description

---

employees/templates/employees/partial/display_reports/display_project_reports.html
employees/templates/employees/partial/display_reports/reports_in_date_for_project_author.html
employees/templates/employees/project_report_list.html
employees/tests/test_views.py

Resolve : https://github.com/Code-Poets/sheetstorm/issues/494
Related: https://github.com/Code-Poets/sheetstorm/pull/517

Feature refactor project reports list view

---

README.md

"deafult" -> default
"<version>" -> "\<version\>"

Bugfix readme typo "deafult"

---

Pipfile.lock
check-environment-packages.sh
employees/tests/test_unit_custom_mixins.py
employees/tests/test_unit_export_data.py
managers/models.py
pylintrc
pytest.ini
sheetstorm/apps.py
users/tests/test_views.py
users/tokens.py
users/views.py
utils/mixins.py

Chore update all project dependecies

---

users/static/users/center_style.css
users/static/users/style.css
users/templates/user_notifications_list.html

Feature rebuild notifications interface
