Code-Poets/sheetstorm

- managers/factories.py
- managers/tests/test_api.py
- managers/urls.py
- managers/views.py
- requirements.lock
- requirements.txt
Resolves https://github.com/Code-Poets/sheetstorm/issues/69
> Bugfix sorting in project names separates upper and lowercase

- employees/common/strings.py
- employees/static/employees/scripts/basic_popup_window.js
- employees/static/employees/style.css
- employees/templates/employees/report_detail.html
- employees/templates/employees/report_list.html
- employees/tests/test_unit_report_view_helper_functions.py
- employees/tests/test_unit_report_viewset.py
- employees/urls.py
- employees/views.py
- users/templates/base.html
- utils/decorators.py
> Feature employees interface

- managers/models.py
- managers/serializers.py
- managers/templates/managers/projects_list.html
- managers/tests/test_unit_managers_apiview.py
- managers/tests/test_unit_model.py
- managers/tests/test_unit_serializer.py
- managers/urls.py
- managers/views.py
- users/templates/base.html
- users/templatetags/user_type_tags.py
> Feature project list view

- employees/common/strings.py
- employees/forms.py
- employees/static/employees/scripts/join_popup_window.js
- employees/templates/employees/report_list.html
- employees/tests/test_unit_project_join_form.py
- employees/tests/test_unit_report_viewset.py
- employees/views.py
> Feature allow employee to join project

- requirements.lock
> Fix django warnings about renamed `psycopg2`

- employees/common/strings.py
- utils/decorators.py
User interface text is stored in enums which are callable objects. Thus trying to access these values results in failed call and an empty string is returned.
This branch adds custom decorator to allow callable objects to be normally displayed in templates by preventing templating system from performing calls.
> Bugfix no text in employees app

- users/templates/base.html
Fixes issues regarding javascript functions crashing on page render.
Resolves #126
> Move javascript related imports in base.html before block content

- RELEASE-NOTES.md
Resolves: https://github.com/Code-Poets/sheetstorm/issues/27
> Chore create release notes 0.1.0

- users/static/users/center_style.css
- users/static/users/scripts/float_menu.js
- users/templates/base.html
> Chore change toggle icon

- managers/static/managers/scripts/delete_project_popup.js
- managers/templates/managers/project_form.html
Fixes acknowledged issues regarding project deletion feature.
For specific details, please refer to commit messages.
Resolves #156
Resolves #155
> Bugfix delete button doesn't work for project

- managers/models.py
- managers/tests/test_unit_project_signals.py
Resolves: https://github.com/Code-Poets/sheetstorm/issues/159
Admin user type shouldn't change to `Manager` after assignee him as a project manager.
> Bugfix repair handlers for admin in handlers

- users/static/users/scripts/float_menu.js
- users/templates/base.html
No issue for this.
The problem was with class name and position of `float menu.js`, because it uses jquery. Before uploaded jquery we was wanted to use float menu.js was running.
> Fixes to base and js script

- employees/common/strings.py
- employees/templates/employees/report_list.html
- employees/tests/test_unit_report_viewset.py
- employees/views.py
Resolves #141 
**Done:**
- If there are no projects available for joining, the form with project selection visible in popup is replaced with appropriate message, preventing user from submitting an empty form resulting in app crash
> Bugfix no project selected on join crash

- employees/static/employees/style.css
- employees/templates/employees/admin_report_detail.html
Resolves: https://github.com/Code-Poets/sheetstorm/issues/173
**Done**
- description field is not resizable
- added css to `admin_report_detail.html`
Size is smaller than you expected @maciejSamerdak I think it was looking different due to localization of description field in form.
> Bugfix add styles to admin report detail

- employees/common/strings.py
- employees/templates/employees/author_report_list.html
Resolves: https://github.com/Code-Poets/sheetstorm/issues/172
**Done**
- Added return button to employee list in template
@Karrp @maciejSamerdak @kbeker @MartynaAnnaGottschling 
Where this button should located, because I am not sure. I have created it above report list but under the header.
> Bugfix add return button on user's report editting screen

- employees/common/strings.py
- employees/static/employees/style.css
- employees/templates/employees/project_report_list.html
- employees/tests/test_unit_report_viewset.py
- employees/urls.py
- employees/views.py
- managers/models.py
- managers/templates/managers/project_detail.html
Introduces list view for all reports from selected project.
Related #130 
**Do not delete this branch until #135 and #134 are merged**
> Feature project report list

- style.sh
Resolves: https://github.com/Code-Poets/sheetstorm/issues/227
I have changed line length settings in isort because default it was 79, and change our import 
`from employees.templatetags.data_structure_element_selectors import get_key_value`
to
`from employees.templatetags.data_structure_element_selectors import /
get_key_value` - `get_key_value` was in new line
> Bugfix-isort-fixing-info

- employees/serializers.py
- employees/templates/employees/report_detail.html
- employees/templates/employees/report_list.html
- employees/tests/test_unit_report_serializer.py
> Bugfix 24 hours validation does not work on report creation

- managers/views.py
Resolves: https://github.com/Code-Poets/sheetstorm/issues/224
I am not sure if this is right solution, but I have checked that our view using this queryset:
`Project.objects.all()` and our for loop is using `object_list` so still the same query is there because view doesn't refresh it. When I've added `object_list.all` in template it is work fine.
> Bugfix-show-all-project-list

- employees/common/strings.py
- employees/serializers.py
- employees/tests/test_unit_report_serializer.py
No issue on that bug. This is bug appeared because of oversight
> Add restriction for non numeric strings to ReportSerializer

- employees/common/constants.py
- employees/common/exports.py
- employees/templates/employees/author_report_list.html
- employees/templates/employees/project_report_list.html
- employees/tests/test_unit_export_data.py
- employees/urls.py
- employees/views.py
- requirements.lock
- requirements.txt
Resolves: https://github.com/Code-Poets/sheetstorm/issues/161
This feature should give us possibility to export reports to excel compatible format. In this case it should be `xlsx` format.
**Done**
- Reports are covnerted to `xlsx` format
- Reports for single user should have `Date , Projects, Task activities, hours, description` columns
- Last row should have functional total hours counter.
- Reports for project should have `Date, Task activities, Hours, Description' columns and sheet per employee
**Unresolved yet**
- Tests for this feature
- View returned all reports without date filtered. I think that it would be better to implement it when those features will be merged : 
https://github.com/Code-Poets/sheetstorm/pull/138
https://github.com/Code-Poets/sheetstorm/pull/139
But I am not …
> Feature add export reports to xlsx

- employees/tests/test_unit_report_viewset.py
> Show day numer as non-zero padded decimal

- employees/common/exports.py
- employees/tests/test_unit_export_data.py
- employees/views.py
- users/factories.py
- utils/tests/test_access_permissions.py
The point is that when manager exported project with all reports they were not sorted at all. This PR fixes it.
> Bugfix sorting exported reports for project and access permissions

- employees/templates/employees/author_report_list.html
- employees/tests/test_views.py
- employees/urls.py
- employees/views.py
- users/templates/users_list.html
- users/views.py
- utils/tests/test_access_permissions.py
Resolves #25
Related #138
Done:
- Author's reports list view now displays reports from single month
- Month navigation bar was introduced to author report list
- User's list view has been updated to properly redirect to author's reports list
> Feature month segregation for author report list

- employees/common/constants.py
- employees/common/exports.py
- employees/tests/test_unit_export_data.py
> Feature group days and add daily hours to xlsx export

- managers/commons/constants.py
- managers/models.py
- managers/tests/test_unit_model.py
Resolves: https://github.com/Code-Poets/sheetstorm/issues/241
I think that removed test is useless because in opinion it is already tested by django, but you guys could say more about it :) Thanks!
> Bugfix - Add validation to stop_date field in project

- find-files-to-refactor.sh
- lint.sh
- manage.py
No issue for that. After @bartoszbetka added deployment to sheetstorm repo `pylint` started to complain about some code and because of bug in `pylint` which does not allow to add ignoring path this had to be done this way how I changed in this PR.
> Disable code inspection on `sheetstorm-deployment` directory

- employees/common/exports.py
- employees/tests/test_unit_exports.py
- requirements.lock
- requirements.txt
resolves: https://github.com/Code-Poets/sheetstorm/issues/240
> Bugfix exporting report description to xls

- employees/tests/test_views.py
- employees/views.py
- utils/mixins.py
- utils/tests/test_mixins.py
…not manager
Resolves https://github.com/Code-Poets/sheetstorm/issues/316
> Bugfix manager can't edit his own reports in projects where he is not manager

- sheetstorm/settings/base.py
A configuration that sends 404 http error causes a lot of spam traffic
which is not usually needed.
> Chore delete the django middleware that is responsible for sending 404 http error to the sentry environment

- employees/tests/test_unit_custom_forms.py
- employees/tests/test_unit_export_data.py
- employees/tests/test_unit_report_model.py
- employees/tests/test_unit_templatetags.py
- managers/tests/test_unit_model.py
- users/tests/test_unit_customuser_model.py
- users/tests/test_unit_template_tags.py
- users/tests/test_unit_validators.py
- users/tests/test_views.py
- utils/tests/test_access_permissions.py
- utils/tests/test_mixins.py
Resolves https://github.com/Code-Poets/sheetstorm/issues/73
> Unify test naming by removing "that" from tests name schema

- employees/forms.py
- employees/tests/test_unit_report_model.py
- users/models.py
Resolves https://github.com/Code-Poets/sheetstorm/issues/29
TODO: Add test that ReportForm.projects field sets initial to project in which last report was created after https://github.com/Code-Poets/sheetstorm/pull/296 is merged.
> Feature default project for new report

- common/convert.py
- employees/forms.py
- employees/templates/employees/author_report_list.html
- employees/templates/employees/project_report_list.html
- employees/templates/employees/report_detail.html
- employees/templates/employees/report_list.html
- employees/tests/test_unit_custom_forms.py
- employees/tests/test_unit_templatetags.py
- managers/templates/managers/project_form.html
- users/templates/user_update.html
- users/templates/users_detail.html
resolves: https://github.com/Code-Poets/sheetstorm/issues/315
> Feature add mask for work hours field in reports form

- employees/forms.py
> Bugfix "---------------" in projects dropdown list in reposr list view

- employees/tests/test_views.py
- employees/views.py
Resolves #366 
Added method for deriving default date value in report creation form. This is how it works:
1. If the month is current, then the value is current day.
2. If there are no reports on this month, the value is the first day of the month.
3. If there are reports on this month, the value is the next day from the most recent report.
4. If the most recent report is from the last day of the month, the value is also the last day of the month.
This can be useful if the user is late on filling reports. The date on previous months defaults to the day after the last report (if possible), so after each post the default date value is raised by one day.
Done:
- Added method for calculating appropriate default date for selected month, based on existing reports.
> Variable default date value on report creation

- employees/views.py
On project joining in report list view, when the form is invalid the response is `render_to_response`.
The problem is, the provided context is insufficient and also the joining feature `project_form` replaces the report's `form`.
This causes an error in `test_custom_report_list_view_should_handle_no_project_being_selected_in_project_form_on_post` unit test at branch `feature-rebuild-user-reports-interface`, because during render the template refers to non-existing fields (since the forms are switched).
**NOTE:** This is not something that can be experienced via the regular use of Sheet Storm. This use case is merely an extra safety measure to prevent app from crashing on post with insufficient form data. Normally this is impossible.
> Fill context on invalid form response

- managers/forms.py
- managers/views.py
> Bugfix add auto assigning manager if he create project

- employees/common/constants.py
- employees/common/exports.py
- employees/templates/employees/author_report_list.html
- employees/templates/employees/project_report_list.html
- employees/templates/employees/report_list.html
- employees/tests/test_unit_export_data.py
- employees/views.py
Resolves https://github.com/Code-Poets/sheetstorm/issues/311
> Feature enable export reports to csv file

- requirements.lock
- requirements.txt
- sheetstorm/settings/base.py
No issue for this, just cleaning usage big library that we don't use now at all.
> Remove `django-allauth` leftovers

- employees/tests/test_unit_custom_mixins.py
- employees/tests/test_views.py
- sheetstorm/urls.py
- users/tests/test_views.py
While cleaning up I have seen that we are still using the same url namespace for two Django apps. This should be avoided if not needed, so I have added the fix. Due to this I have discovered there were some places in which we were using hardcoded urls, so I have switched them to use `reverse`.
> Fix urls namespace and add reverse to missing usages in tests

- employees/tests/test_views.py
- employees/views.py
Resolves: https://github.com/Code-Poets/sheetstorm/issues/445
I had an error after clean database, when I wanted to get to my reports I had an Attribute error, I wasn't sure why but on debugging I found that queryset returned some reports. I found that add this filter resolve the problem.
> Bugfix custom report list

- employees/common/constants.py
- employees/common/exports.py
- employees/tests/test_unit_export_data.py
- employees/views.py
Resolves: https://github.com/Code-Poets/sheetstorm/issues/436
The problem was only in csv in project reports.
> Bugfix total hours in csv in project reports

- load_initial_data.sh
- users/management/commands/load_initial_data.py
Resolves: https://github.com/Code-Poets/sheetstorm/issues/449
When we create reports in initial data we didn't pass task activities, due to this `TaskActivityTypeFactory` was creating new task activity object from this values `"Review", "Backend Development", "Frontend Development", "Meeting"`
> Bugfix add task activities to Report in initial data

- utils/tests/test_mixins.py
There is no issue for that. Problem occurred because today is last day in month and in tests was hard-coded November and as we all know November has 30 days:)
> Bugfix add freeze_time decorator to work percentage time mixin tests

- managers/forms.py
- managers/tests/test_views.py
- managers/views.py
- utils/tests/test_access_permissions.py
Resolves: https://github.com/Code-Poets/sheetstorm/issues/462
**Should have done**
- managers field is optional, user of request is always set as manager.
- when we go to update the project view, we could see all managers and if we want to update it, we do not remove the manager who created the project.
> Bugfix managers field in project admin form

- coverage-config
- e2e.sh
- full-check.sh
No issue for that.
Long story short - after selenium `e2e` tests had been added, our unit tests coverage dropped significantly (because `features/` folder had been not marked as excluded in `coverage-config`)
This PR:
1. Fixes `coverage-config`
2. Adds coverage report for `e2e` tests
> Improve coverage settings

- employees/common/strings.py
- employees/forms.py
- employees/static/employees/scripts/load_activities_for_project.js
- employees/templates/employees/partial/task_activity_list.html
- employees/templates/employees/report_list.html
- employees/tests/test_views.py
- employees/urls.py
- employees/views.py
Related: https://github.com/Code-Poets/sheetstorm/pull/460
On this branch I added dynamic filter for task activity list per each project.
After approving this PR: https://github.com/Code-Poets/sheetstorm/pull/460 I will start to create a panel admin view for task activities.
After `full_check` you can notice two failed test but It has been reported because it occured on master branch.
> Feature add dynamic filter for task activities per project

- pylintrc
There is no issue for this. We have to disable `cyclic-import` becuase of https://github.com/PyCQA/pylint/issues/850
> Bugfix disable `cyclic-import` in pylintrc config

- managers/templates/managers/project_task_activities.html
No issue for this.
When I was trying to delete some activity which wasn't first I couldn't do it, all the time it was deleted first position in displayed list. I think because our button was working for all form with the same id and it took always first form
> Bugfix remove task activity from project

- managers/models.py
- managers/tests/test_unit_project_signals.py
Resolve: https://github.com/Code-Poets/sheetstorm/issues/70
When project 'stop_date is not null' then it can't be suspended
> Bugfix stop_date and suspended field in project

- users/admin.py
After removing few CustomUser fields due to RODO, there are some residue left in `users/admin.py`. It causes not working admin site, while trying to edit user:
So I only removed these fields from `CustomUser PERSONAL_INFO`
> Bugfix remove CustomUser model fields from admin panel

- Pipfile
- Pipfile.lock
- employees/templates/employees/author_report_list.html
- employees/templates/employees/project_report_detail.html
- employees/templates/employees/project_report_list.html
- employees/templates/employees/report_detail.html
- employees/templates/employees/report_list.html
- managers/templates/managers/project_form.html
- managers/templates/managers/project_task_activities.html
- managers/templates/managers/projects_list.html
- sheetstorm/settings/base.py
- users/templates/account_confirmation/confirmation.html
- users/templates/accounts/success-registration.html
- users/templates/base.html
- users/templates/registration/login.html
- users/templates/signup.html
- users/templates/user_update.html
- users/templates/users_detail.html
This is part of #507 issue. First part with django settings is already merged into master. This pull request is especially to test all views by @Karrp because all script and stylesheets have changed tags.
> Bugfix scripts and links security vulnerabilities

- employees/common/constants.py
- employees/common/exports.py
- employees/tests/test_unit_export_data.py
Resolve: https://github.com/Code-Poets/sheetstorm/issues/531
Problem could be because `openpyxl` has some problem with converting formulas but I am not sure it in 100%, because when I save file again on computer without any changes, size increase on 300kb and then we could see formulas and values on gmail. 
I removed all formulas and change it to values.
> Bugfix remove formulas from hours fields

- employees/templates/employees/partial/display_reports/reports_in_date_for_author.html
- employees/tests/test_views.py
There is no issue fo this.
Fixes:
- admin now can delete his own report like any other employee
- after editing own report admin is redirected to "my reports" site
> Bugfix redirect admin to his own report edition

- RELEASE-NOTES.md
- employees/common/exports.py
- employees/tests/test_unit_export_data.py
Fix issue which came from sentry: http://35.242.195.123/sentry/sheetstorm/issues/5132/
> Bugfix illigal characters from description

- employees/tests/test_views.py
- managers/forms.py
- managers/tests/test_views.py
- managers/views.py
- users/forms.py
- users/models.py
- users/tests/test_unit_customuser_model.py
- users/tests/test_unit_customuser_signals.py
- users/tests/test_views.py
- users/views.py
Fixes multiple issues regarding deactivating users by marking them as inactive using the _is_active_ field in _**CustomUser**_ model.
Now after deactivating a user through the admin panel, the following will happen:
- The user won't be listed on the employees' list anymore
- His user type will be changed to an employee and all of his privileges will be disabled
- The user will be removed from all projects as both member and a manager
- All of his reports will remain intact and will be displayed for his former projects
- It will be impossible to pick this user as a member or manager during project creation and editing
It is also confirmed that deactivation results in disabling notifications regarding the user and an appropriate unit test has been added.
> Bugfix inactive users are displayed in app

- employees/common/strings.py
- employees/static/employees/style.css
- employees/templates/employees/partial/projects_work_percentage.html
- employees/tests/test_unit_report_model.py
- users/models.py
- utils/mixins.py
- utils/tests/test_mixins.py
The monthly work hours are now always calculated form the beginning of the month.
The information about actual amount of hours spent on project is displayed next to the percentage.
> Feature improve monthly hours stats

- users/templates/users_list.html
- users/tests/test_views.py
- users/views.py
Changes ordering in employees list in following hierarchy:
**user type** -> **last name** -> **first name** -> **email**
> Change ordering in employees' list

- RELEASE-NOTES.md
- employees/tests/test_views.py
- employees/views.py
`_get_default_date(self)` has been removed from view and initial date now defaults to `timezone.now().date()`
> Bugfix default date on report creation
